version: '3'

services:
  nginx:
    build: nginx
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "~/Documents/www:/var/www/html:delegated"
    tty: true

  php:
    build: php
    env_file: docker-env
    ports:
      - "9000:9000"
    volumes:
      - "~/Documents/www:/var/www/html:delegated"
    tty: true

  mysql:
    image: mariadb:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    tty: true

#  elk:
#    image: willdurand/elk
#    env_file: docker-env
#    ports:
#      - "81:80"
#    volumes:
#      - "~/Documents/www:/var/www/html:delegated"
#      - "./docker/elk/logstash:/etc/logstash"
#      - "./docker/elk/logstash/patterns:/opt/logstash/patterns"
#    tty: true

  maildev:
    image: djfarrelly/maildev:latest
    env_file: docker-env
    ports:
      - "1080:80"
    tty: true

volumes:
  mysql: {}