version: '2.1'

services:
  nginx:
    image: nginx:latest
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/servers:/etc/nginx/conf.d"
      - "~/path/to/www/app/logs/nginx/:/var/log/nginx"
    volumes_from:
      - php
    tty: true

  php:
    build: php
    env_file: docker-env
    ports:
      - "9000:9000"
    volumes:
      - "~/path/to/www:/var/www/html"
      - "./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
    tty: true

  percona:
    image: percona:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "./docker/percona/custom.cnf:/etc/mysql/conf.d/custom.cnf"
    tty: true

  elk:
    image: willdurand/elk
    env_file: docker-env
    ports:
      - "81:80"
    volumes:
      - "./docker/elk/logstash:/etc/logstash"
      - "./docker/elk/logstash/patterns:/opt/logstash/patterns"
    volumes_from:
      - php
      - nginx
    tty: true
